### ISSUE TITLE
Linux下能做成守护进程嘛..

### ISSUE THREAD

**Issue by shuyabin** [ouqiang/gocron#10]
直接执行gocron web  会一直阻塞停在那里..请问一下大腿.怎么能做成守护进程...

**Comment by ouqiang** [comment]
可以用Supervisor管理进程, 当进程挂掉后Supervisor能自动重启

**Comment by shuyabin** [comment]
我试了一下. 我如果不在gocron的安装目录
![image](https://user-images.githubusercontent.com/14884581/29238080-a249a876-7f5f-11e7-98c2-b8c98afc7bfc.png)
执行没反应。。 
在二进制目录汇总就可以
![image](https://user-images.githubusercontent.com/14884581/29238107-12910e26-7f60-11e7-893f-4c4bd0d7498c.png)


在Supervisor中
![image](https://user-images.githubusercontent.com/14884581/29238095-cde8893e-7f5f-11e7-88e0-2c421154df72.png)

![image](https://user-images.githubusercontent.com/14884581/29238100-f656d01a-7f5f-11e7-8ec0-26022cc7e596.png)

请问大腿-哪里配置错了嘛...

**Comment by ouqiang** [comment]
Supervisor中需指定程序运行时目录，增加directory配置就可以了。发自我的iPhone------------------ 原始邮件 ------------------发件人: shuyabin  <notifications@github.com>发送时间: 2017年8月12日 13:13收件人: ouqiang/gocron <gocron@noreply.github.com>抄送: qiang.ou <qingqianludao@gmail.com>, Comment <comment@noreply.github.com>主题: 回复：[ouqiang/gocron] Linux下能做成守护进程嘛.. (#10)我试了一下. 我如果不在gocron的安装目录

执行没反应。。
在二进制目录汇总就可以

在Supervisor中


请问大腿-哪里配置错了嘛...

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ouqiang/gocron","title":"ouqiang/gocron","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ouqiang/gocron"}},"updates":{"snippets":[{"icon":"PERSON","message":"@shuyabin in #10: 我试了一下. 我如果不在gocron的安装目录\r\n![image](https://user-images.githubusercontent.com/14884581/29238080-a249a876-7f5f-11e7-98c2-b8c98afc7bfc.png)\r\n执行没反应。。 \r\n在二进制目录汇总就可以\r\n![image](https://user-images.githubusercontent.com/14884581/29238107-12910e26-7f60-11e7-893f-4c4bd0d7498c.png)\r\n\r\n\r\n在Supervisor中\r\n![image](https://user-images.githubusercontent.com/14884581/29238095-cde8893e-7f5f-11e7-88e0-2c421154df72.png)\r\n\r\n![image](https://user-images.githubusercontent.com/14884581/29238100-f656d01a-7f5f-11e7-8ec0-26022cc7e596.png)\r\n\r\n请问大腿-哪里配置错了嘛..."}],"action":{"name":"View Issue","url":"https://github.com/ouqiang/gocron/issues/10#issuecomment-321958342"}}}

**Comment by shuyabin** [comment]
非常感谢。可以了.
